[tool.black]
line-length = 100
target-version = ['py311', 'py312', 'py313']
include = '\.pyi?$'
exclude = '''
/(
		\.git
	| \.hg
	| \.mypy_cache
	| \.nox
	| \.tox
	| \.venv
	| _build
	| buck-out
	| build
	| dist
	| __pycache__
)/
'''
