name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-skcc-calculator:
    name: Test SKCC Calculator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          
      - name: Test ADIF parsing
        run: |
          cd backend/app
          python -m pytest tests/test_adif.py -v
          
      - name: Test award calculation
        run: |
          cd backend/app
          python -m pytest tests/test_awards.py -v
          
      - name: Test SKCC rules
        run: |
          cd backend/app
          python -m pytest tests/test_centurion_rules.py -v
          
      - name: Test normalization
        run: |
          cd backend/app
          python -m pytest tests/test_normalization.py -v
          
      - name: Lint with ruff (non-blocking)
        run: |
          pip install ruff
          ruff check backend/app || echo "Linting issues found but not blocking CI"
          
      - name: Test GUI imports (basic)
        run: |
          python -c "
          import sys
          sys.path.append('scripts')
          try:
              import tkinter
              print('✓ Tkinter available')
          except ImportError:
              print('⚠ Tkinter not available in headless environment (expected)')
          
          # Test core SKCC module imports
          sys.path.append('backend/app')
          from services.skcc import parse_adif, fetch_roster_live, calculate_awards
          print('✓ Core SKCC modules import successfully')
          "

